# ==========================================================================
# CRE WORKFLOW SETTINGS FILE - Go Implementation
# ==========================================================================
# Workflow-specific settings for CRE CLI targets.
# This Go implementation uses EVM Log Trigger (fully supported)

staging-settings:
  user-workflow:
    workflow-name: "safe-update-go-staging"
  workflow-artifacts:
    workflow-path: "./main.go"
    config-path: "./config.json"
    secrets-path: ""

production-settings:
  user-workflow:
    workflow-name: "safe-update-go-production"
  workflow-artifacts:
    workflow-path: "./main.go"
    config-path: "./config.json"
    secrets-path: ""
